In [55]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

In [56]:
data = {
    "name":["A","C","D","B","E","A","E","C"],
    "dept_id":["s1","s4","s5","s2","s3","s1","s4","s5"],
    "d_name" :["Analyst","Developer","Engineer","Trainer","UI Developer","Developer","Engineer","Analyst"],
    "salary" :[15000,20000,23000,18000,21000,19000,25000,27000]
}

In [57]:
df = pd.DataFrame(data)

In [58]:
df

,name,dept_id,d_name,salary
0,A,s1,Analyst,15000
1,C,s4,Developer,20000
2,D,s5,Engineer,23000
3,B,s2,Trainer,18000
4,E,s3,UI Developer,21000
5,A,s1,Developer,19000
6,E,s4,Engineer,25000
7,C,s5,Analyst,27000


In [59]:
x = df.drop(columns='salary')
y = df['salary']

In [60]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8,random_state=42)

In [61]:
df

,name,dept_id,d_name,salary
0,A,s1,Analyst,15000
1,C,s4,Developer,20000
2,D,s5,Engineer,23000
3,B,s2,Trainer,18000
4,E,s3,UI Developer,21000
5,A,s1,Developer,19000
6,E,s4,Engineer,25000
7,C,s5,Analyst,27000


# Scenario 1

* Error --> ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,)


In [62]:
encoder = OrdinalEncoder(categories=[['Developer','Analyst','Enginneer','Trainer',"UI Developer"],["s1",'s2','s5','s4','s3']],
                         handle_unknown="use_encoded_value",
                         unknown_value=-1
                         )

encoder.fit_transform(xtrain[['d_name','dept_id']])
# encoder.fit_transform(xtrain[['d_name','dept_id',"name"]])

#Error --> ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,)

array([[ 1.,  0.],
       [ 1.,  2.],
       [-1.,  2.],
       [ 4.,  4.],
       [ 3.,  1.],
       [-1.,  3.]])

# Scenario 2

* InvalidIndexError: (['dept_id'], ['d_name'])
* Every value is unknown now! So ,it assigns -1 for all the values. 

In [63]:
encoder = OrdinalEncoder(categories=[['Developer','Analyst','Enginneer','Trainer',"UI Developer"],["s1",'s2','s5','s4','s3']],
                         handle_unknown="use_encoded_value",
                         unknown_value=-1
                         )

# encoder.fit_transform(xtrain[['dept_id'],['d_name']])
encoder.fit_transform(xtrain[['dept_id','d_name']])


array([[-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.]])

# Scenario 3

* If the value on the Category present it gives a meaningful value if not present it gives (-1)

In [64]:
encoder = OrdinalEncoder(categories=[['Developer','Analyst','Enginneer','AI Engineer'],["s1",'s2','s5','s4','s3']],
                         handle_unknown="use_encoded_value",
                         unknown_value=-1
                         )

encoder.fit_transform(xtrain[['d_name','dept_id']])
encoder.transform(xtest[['d_name','dept_id']])

array([[0., 3.],
       [0., 0.]])

In [65]:
encoder

,"categories categories: 'auto' or a list of array-like, default='auto'Categories (unique values) per feature:- 'auto' : Determine categories automatically from the training data.- list : ``categories[i]`` holds the categories expected in the ith column. The passed categories should not mix strings and numeric values, and should be sorted in case of numeric values.The used categories can be found in the ``categories_`` attribute.","[['Developer', 'Analyst', ...], ['s1', 's2', ...]]"
,"handle_unknown handle_unknown: {'error', 'use_encoded_value'}, default='error'When set to 'error' an error will be raised in case an unknowncategorical feature is present during transform. When set to'use_encoded_value', the encoded value of unknown categories will beset to the value given for the parameter `unknown_value`. In:meth:`inverse_transform`, an unknown category will be denoted as None... versionadded:: 0.24",'use_encoded_value'
,"unknown_value unknown_value: int or np.nan, default=NoneWhen the parameter handle_unknown is set to 'use_encoded_value', thisparameter is required and will set the encoded value of unknowncategories. It has to be distinct from the values used to encode any ofthe categories in `fit`. If set to np.nan, the `dtype` parameter mustbe a float dtype... versionadded:: 0.24",-1
,"dtype dtype: number type, default=np.float64Desired dtype of output.",<class 'numpy.float64'>
,"encoded_missing_value encoded_missing_value: int or np.nan, default=np.nanEncoded value of missing categories. If set to `np.nan`, then the `dtype`parameter must be a float dtype... versionadded:: 1.1",nan
,"min_frequency min_frequency: int or float, default=NoneSpecifies the minimum frequency below which a category will beconsidered infrequent.- If `int`, categories with a smaller cardinality will be considered infrequent.- If `float`, categories with a smaller cardinality than `min_frequency * n_samples` will be considered infrequent... versionadded:: 1.3 Read more in the :ref:`User Guide <encoder_infrequent_categories>`.",None
,"max_categories max_categories: int, default=NoneSpecifies an upper limit to the number of output categories for each inputfeature when considering infrequent categories. If there are infrequentcategories, `max_categories` includes the category representing theinfrequent categories along with the frequent categories. If `None`,there is no limit to the number of output features.`max_categories` do **not** take into account missing or unknowncategories. Setting `unknown_value` or `encoded_missing_value` to aninteger will increase the number of unique integer codes by one each.This can result in up to `max_categories + 2` integer codes... versionadded:: 1.3 Read more in the :ref:`User Guide <encoder_infrequent_categories>`.",None
Name,Type,Value
categories_ categories_: list of arraysThe categories of each feature determined during ``fit`` (in order ofthe features in X and corresponding with the output of ``transform``).This does not include categories that weren't seen during ``fit``.,list,"[array(['Devel... dtype=object), array(['s1', ... dtype=object)]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](2,)","['d_name','dept_id']"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 1.0,int,2
